### ISSUE TITLE
Gradle runs program fine, but program seems to fail on Intellij

### ISSUE THREAD

**Issue by kieron560** [nus-cs2103-AY2021S2/forum#113]
For some reason, my Intellij doesn't seem to work, and gives me a ton of error, yet when I run the Gradle script, it seems to work fine. For example, when this is my start method in my Main class as per the JavaFX tutorial (exactly the same). This seems to somehow pop up out of nowhere because I'm sure my IDE could run a few days ago...

```
@Override
    public void start(Stage stage) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(Main.class.getResource("/view/MainWindow.fxml"));
            AnchorPane ap = fxmlLoader.load();
            Scene scene = new Scene(ap);
            stage.setScene(scene);
            fxmlLoader.<MainWindow>getController().setDuke(duke);
            stage.show();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```
yet it shows this error:

```
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:973)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Location is not set.
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2459)
	at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
	at Main.start(Main.java:16)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	... 1 more
```
But when I built and run with gradle --> `Tasks/build/build` ,`ip [run]`, it works fine! The JAR file created with the Gradle works too. Another thing is the testcases, I would get this error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/junit/platform/launcher/TestExecutionListener
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.intellij.junit5.JUnit5IdeaTestRunner.createListeners(JUnit5IdeaTestRunner.java:39)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:31)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.launcher.TestExecutionListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 13 more
```
But once again, running Gradle's `verficiation/test` works and passes my testcase just fine.

Is this a cause for concern, because my code is literally the same and yet these error that are not present before are here suddenly.

**Comment by damithc** [comment]
Check if your Intellij is using Gradle to build/run the code (see [this comment](https://github.com/nus-cs2103-AY2021S2/forum/issues/97#issuecomment-772277272)). If it is, there is a better chance that both will work the same way.

**Comment by kieron560** [comment]
Yes, I'm using Gradle as the default for both `build and run` and `run tests`.
![image](https://user-images.githubusercontent.com/60651926/107110337-f4ad4c80-6881-11eb-864c-9ccc2f94cff1.png)

**Comment by w2vgd** [comment]
@kieron560 Have you tried changing the `mainClassName` under `application` in your `build.gradle` file to 
`mainClassName="Launcher"` (assuming you are following the tutorial exactly) instead of the default `Duke`?

And also do note that if you are running the application in intellij, you have to run the `Launcher` class intead of the `Main` class if not there will be an error that says `JavaFX runtime components are missing, and are required to run this application` (although I am not really sure what cause this error).

**Comment by kieron560** [comment]
Yes! my `mainClassName` is "Launcher", and I've been trying to run  using the Launcher `main()` method haha
What I'm confused is that the error says `Location is not set`, and yes when I tried  to `System.out.println(Main.class.getResource("/view/MainWindow.fxml"))` I get a `null`, and hence I'm really confused since Gradle should be using the same code (and the tutorial literally works before with the same code) and yet for some reason my IDE is popping up all these errors now haha

**Comment by w2vgd** [comment]
Is your resources folder marked as `Resources Root` as shown by the icon below?

![image](https://user-images.githubusercontent.com/65358857/107111366-99cc2300-688a-11eb-8020-4191c97b1bcd.png)

If it is not yet marked, you may want to try marking it as the `Resources Root` as follows (there should be an option for Resources Root if you have yet to mark it):
![image](https://user-images.githubusercontent.com/65358857/107111406-df88eb80-688a-11eb-9bc9-008cfec23a1d.png)

**Comment by kieron560** [comment]
oh my god. What the... IT WORKS
Thank you so much sir...
But actually what does marking the folder as `Resource Root` does ah out of curiousity? And why can Gradle run it fine, but the IDE doesnt seem to know it's a resource folder?

Also really ,thanks, but my tests are still goners though... This is my screenshot of my folder structure just in case I didn't mark it again...

![image](https://user-images.githubusercontent.com/60651926/107111471-50c89e80-688b-11eb-9512-7cec91788e34.png)

**Comment by w2vgd** [comment]
> But actually what does marking the folder as `Resource Root` does ah out of curiousity? And why can Gradle run it fine, but the IDE doesnt seem to know it's a resource folder?

You may read up more about such content roots from the official IntelliJ documentation [here](https://www.jetbrains.com/help/idea/content-roots.html#folder-categories) or I also found this [stackoverflow answer](https://stackoverflow.com/questions/39254216/when-would-i-use-the-mark-directory-as-option-in-intellij-idea/39255116) quite useful to understand.

> Also really ,thanks, but my tests are still goners though... This is my screenshot of my folder structure just in case I didn't mark it again...

Does your test folder directly mirror the original main folder? In this case, for example, is your structure for your `Duke` class in the `main` folder as follows:
`main` -> `java` -> `duke` -> `Duke.java` ?
and similarly for your `Event` and `Todo` classes. They have to be in the exact same folder structure as the `main` folder.

**Comment by kieron560** [comment]
Hmm, doesn't seem to be working though... But it's alright for now I guess. I'll fix the testcase bugs in the future, and focus on this weeks iP levels now that I can run properly on my IDE at least. Thank you so much!!
